#GET http://localhost:3001/api/blogs
#DELETE http://localhost:3001/api/blogs/2

DELETE http://localhost:3001/api/blogs/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uLm1vcm96QGhlbHNpbmtpLmZpIiwiaWQiOjMsImlhdCI6MTYzNTMzMzEwMn0.kZaPBj1VnZ6H3R3rujIBkcZaLXVTHb95dnEJxoOxWMs

{
    "username": "anton.moroz@helsinki.fi",
    "password": "salainen"
}
