POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjhhbnRvbm1AZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTYzNTQzMzQ4MH0.9phhQdiI5bZdU_oB5tbzHYXZhXhRXvHCpzALPJDR9aA

{
    "year": 2020,
    "author": "Anttoni",
    "url": "#",
    "title": "Päiväkirjani"
}
