POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjhhbnRvbm1AZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTYzNTUwNjE5N30.RWYHICOjgQkNK5Gr1MXjiWQ-XbJuQstGkCG-7d5OgQ4

{
    "year": 2020,
    "author": "DannyBoyAbramovich",
    "url": "#",
    "title": "React18News"
}
