POST http://localhost:3001/api/notes
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjhhbnRvbm1AZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTYzNTQ1MjM5MH0.NAw-XdPo0w1GVg_UuAzbGBI-kXp2NyikFVfAo3SwKmg

{
    "content": "Not very important :)",
    "important": false
}
