PUT http://localhost:3001/api/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uLm1vcm96QGhlbHNpbmtpLmZpIiwiaWQiOjIsImlhdCI6MTYzNTUyNzA4M30.Un5aNel4yiH7ja99PPMe8cn10S-bKTEn81viugBKcfE

{
  "read": false
}
